version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 127.0.0.1:${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    # TODO: add auth

  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    environment: 
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-dummybottoken}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummyopenaiapikey}
      - RETRIEVAL_PLUGIN_BEARER_TOKEN=${RETRIEVAL_PLUGIN_BEARER_TOKEN:-dummyretrievalpluginbearertoken}
      - ELASTICSEARCH_ENDPOINT=${ELASTICSEARCH_ENDPOINT:-http://elasticsearch:9200}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-dummyelasticsearchusername}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-dummyelasticsearchpassword}
    depends_on:
      - mongo